# docker-compose.yml
version: "3.9"

services:
  wtw:
    build: .
    container_name: wtw
    environment:
      - IPGEO_API_KEY=${IPGEO_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - .:/app
    command: ["--ip"]
